version: "3.7"
services:
  db: 
    image: postgres
    container_name: dbPostgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5439:5432" 
