version: "3.7"
services:
  db: 
    image: postgres
    container_name: database
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    volumes:
      - ./pg_database:/var/lib/postgresql/data
    ports:
      - "5439:5432" 
